export const subjects = [
  (fe = [
    { title: 'Enginnering Maths', teacher: 'Shilpa Dingankar' },
    { title: 'Enginnering Physics', teacher: 'Nisarg Vyas' },
    { title: 'Enginnering Chemistry', teacher: 'Bhagyashree Chari' },
    { title: 'Basic Electrical Engineering', teacher: 'Anchukrishnan Pillai' },
    { title: 'Enginnering Mechanics', teacher: '' },
    { title: 'Enginnering Maths', teacher: 'Shilpa Dingankar' },
    { title: 'Enginnering Maths', teacher: 'Shilpa Dingankar' },
  ]),
  (seit = [
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
  ]),
  (secse = [
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
  ]),
  (seextc = [
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
  ]),
  (teit = [
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
  ]),
  (tecse = [
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
  ]),
  (teextc = [
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
  ]),
  (beit = [
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
  ]),
  (becse = [
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
  ]),
  (beextc = [
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
    { title: '', teacher: '' },
  ]),
];
